
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wiproleakageprediction-train
  annotations:
    scenarios.ai.sap.com/description: "This scenario predicts the water leakage based on the various parameters such as flow and pressure"
    scenarios.ai.sap.com/name: "wiproleakageprediction-sc"
    executables.ai.sap.com/description: "Python scikit learn based code "
    executables.ai.sap.com/name: "wiproleakageprediction-train-exec"
    artifacts.ai.sap.com/wiproleakageprediction-data.kind: "dataset"
    artifacts.ai.sap.com/wiproleakageprediction-model.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "wiproleakageprediction"
    executables.ai.sap.com/id: "wiproleakageprediction"
    ai.sap.com/version: "1.0.0"
spec:
  imagePullSecrets:
    - name: docker-registry-secret
  entrypoint: wlp-train-entry-point
  templates:
    - name: wlp-train-entry-point
      metadata:
        labels:
          ai.sap.com/resourcePlan: starter
      inputs:
        artifacts:
          - name: wiproleakageprediction-data
            path: /app/data/
      outputs:
        artifacts:
          - name: wiproleakageprediction-model
            path: /app/model
            globalName: wiproleakageprediction-model
            archive:
              none: {}
      container:
        image: "docker.io/hyperscalaruser/wlp-train:0.0.1"
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - >
            set -e && echo "---Start Training---" && python /app/src/LeakageModel.py && ls -lR /app/model && echo "---End Training---"
